const components = [
  {
    name: 'ACH Direct Debit',
    paymentType:'directDebit',
    paymentFlow: 'direct',
    countries: ['US'],
    currencies: ['USD'],
    recurring: true,
    refunds: true,
    partialRefunds: true,
    captures: false,
    partialCaptures: false,
    chargebacks: true,
    url: 'https://docs.adyen.com/payment-methods/ach-direct-debit'
  },
  {
    name: 'After Pay',
    paymentType:'openInvoice',
    paymentFlow: 'direct',
    countries: ['NL', 'BE'],
    currencies: ['EUR'],
    recurring: false,
    refunds: false,
    partialRefunds: false,
    captures: false,
    partialCaptures: false,
    chargebacks: false,
    url: 'https://docs.adyen.com/payment-methods/afterpay'
  },
  {
    name: 'Afterpay Touch',
    paymentType: 'wallet',
    paymentFlow: 'redirect',
    countries: ['AU', 'NZ'],
    currencies: ['AUD', 'NZD'],
    recurring: false,
    refunds: true,
    partialRefunds: true,
    captures: false,
    partialCaptures: false,
    chargebacks: false,
    url: 'https://docs.adyen.com/payment-methods/afterpaytouch'
  },
  {
    name: 'Alipay',
    paymentType:'wallet',
    paymentFlow: 'redirect',
    countries: ['CN'],
    currencies: ['multiple'],
    recurring: false,
    refunds: true,
    partialRefunds: true,
    captures: false,
    partialCaptures: false,
    chargebacks: false,
    url:'https://docs.adyen.com/payment-methods/alipay'
  },
  {
    name: 'AlipayHK',
    paymentType:'wallet',
    paymentFlow: 'redirect',
    countries: ['HK'],
    currencies: ['HKD'],
    recurring: false,
    refunds: true,
    partialRefunds: true,
    captures: false,
    partialCaptures: false,
    chargebacks: true,
    url:''
  },
  {
    name: '',
    paymentType:'',
    paymentFlow: '',
    countries: [],
    currencies: [],
    recurring: false,
    refunds: false,
    partialRefunds: false,
    captures: false,
    partialCaptures: false,
    chargebacks: false,
    url:''
  },
]