export const componentList = [
  {
    name: 'ACH Direct Debit',
    paymentType:'directDebit',
    paymentFlow: 'direct',
    countries: ['US'],
    currencies: ['USD'],
    recurring: true,
    refunds: true,
    partialRefunds: true,
    captures: false,
    partialCaptures: false,
    chargebacks: true,
    url: 'https://docs.adyen.com/payment-methods/ach-direct-debit'
  },
  {
    name: 'After Pay',
    paymentType:'openInvoice',
    paymentFlow: 'direct',
    countries: ['NL', 'BE'],
    currencies: ['EUR'],
    recurring: false,
    refunds: false,
    partialRefunds: false,
    captures: false,
    partialCaptures: false,
    chargebacks: false,
    url: 'https://docs.adyen.com/payment-methods/afterpay'
  },
  {
    name: 'Afterpay Touch',
    paymentType: 'wallet',
    paymentFlow: 'redirect',
    countries: ['AU', 'NZ'],
    currencies: ['AUD', 'NZD'],
    recurring: false,
    refunds: true,
    partialRefunds: true,
    captures: false,
    partialCaptures: false,
    chargebacks: false,
    url: 'https://docs.adyen.com/payment-methods/afterpaytouch'
  },
  {
    name: 'Alipay',
    paymentType:'wallet',
    paymentFlow: 'redirect',
    countries: ['CN'],
    currencies: ['multiple'],
    recurring: false,
    refunds: true,
    partialRefunds: true,
    captures: false,
    partialCaptures: false,
    chargebacks: false,
    url:'https://docs.adyen.com/payment-methods/alipay'
  },
  {
    name: 'AlipayHK',
    paymentType:'wallet',
    paymentFlow: 'redirect',
    countries: ['HK'],
    currencies: ['HKD'],
    recurring: false,
    refunds: true,
    partialRefunds: true,
    captures: false,
    partialCaptures: false,
    chargebacks: true,
    url:'https://docs.adyen.com/payment-methods/alipayhk'
  },
  {
    name: 'Apple Pay',
    paymentType:'wallet',
    paymentFlow: 'direct',
    countries: ['international'],
    currencies: ['multiple'],
    recurring: true,
    refunds: true,
    partialRefunds: true,
    captures: true,
    partialCaptures: true,
    chargebacks: true,
    url:'https://docs.adyen.com/payment-methods/apple-pay'
  },
  {
    name: 'BACS Direct Debit',
    paymentType:'directDebit',
    paymentFlow: 'redirect',
    countries: ['GB'],
    currencies: ['GBP'],
    recurring: true,
    refunds: true,
    partialRefunds: true,
    captures: false,
    partialCaptures: false,
    chargebacks: true,
    url:'https://docs.adyen.com/payment-methods/bacs'
  },
  {
    name: 'Bancontact card',
    paymentType:'',
    paymentFlow: '',
    countries: [],
    currencies: [],
    recurring: false,
    refunds: false,
    partialRefunds: false,
    captures: false,
    partialCaptures: false,
    chargebacks: false,
    url:'https://docs.adyen.com/payment-methods/bancontact/bancontact-card'
  },
  {
    name: 'Bancontact mobile',
    paymentType:'',
    paymentFlow: '',
    countries: [],
    currencies: [],
    recurring: false,
    refunds: false,
    partialRefunds: false,
    captures: false,
    partialCaptures: false,
    chargebacks: false,
    url:'https://docs.adyen.com/payment-methods/bancontact/bancontact-mobile'
  },
  {
    name: 'Boleto Bancario',
    paymentType:'cashAndAtm',
    paymentFlow: 'voucher',
    countries: ['BR'],
    currencies: ['BRL'],
    recurring: false,
    refunds: false,
    partialRefunds: false,
    captures: false,
    partialCaptures: false,
    chargebacks: false,
    url:'https://docs.adyen.com/payment-methods/boleto-bancario'
  },
  {
    name: 'Cards',
    paymentType:'',
    paymentFlow: '',
    countries: [],
    currencies: [],
    recurring: false,
    refunds: false,
    partialRefunds: false,
    captures: false,
    partialCaptures: false,
    chargebacks: false,
    url:'https://docs.adyen.com/payment-methods/cards'
  },
  {
    name: 'Stored Card Details',
    paymentType:'',
    paymentFlow: '',
    countries: [],
    currencies: [],
    recurring: false,
    refunds: false,
    partialRefunds: false,
    captures: false,
    partialCaptures: false,
    chargebacks: false,
    url:'https://docs.adyen.com/checkout/tokenization/create-and-use-tokens'
  },
  {
    name: 'Dragonpay',
    paymentType:'',
    paymentFlow: '',
    countries: [],
    currencies: [],
    recurring: false,
    refunds: false,
    partialRefunds: false,
    captures: false,
    partialCaptures: false,
    chargebacks: false,
    url:''
  },
  {
    name: 'Dotpay',
    paymentType:'onlineBanking',
    paymentFlow: 'redirect',
    countries: ['PL'],
    currencies: ['PLN'],
    recurring: false,
    refunds: true,
    partialRefunds: false,
    captures: false,
    partialCaptures: false,
    chargebacks: false,
    url:'https://docs.adyen.com/payment-methods/dotpay'
  },
  {
    name: 'Entercash',
    paymentType:'',
    paymentFlow: '',
    countries: [],
    currencies: [],
    recurring: false,
    refunds: false,
    partialRefunds: false,
    captures: false,
    partialCaptures: false,
    chargebacks: false,
    url:''
  },
  {
    name: 'EPS',
    paymentType:'',
    paymentFlow: '',
    countries: [],
    currencies: [],
    recurring: false,
    refunds: false,
    partialRefunds: false,
    captures: false,
    partialCaptures: false,
    chargebacks: false,
    url:''
  },
  {
    name: 'GCash - One Time Purchase',
    paymentType:'wallet',
    paymentFlow: 'redirect',
    countries: ['PH'],
    currencies: ['PHP'],
    recurring: true,
    refunds: true,
    partialRefunds: true,
    captures: false,
    partialCaptures: false,
    chargebacks: false,
    url:'https://docs.adyen.com/payment-methods/gcash?tab=%23one_time_purchase_1'
  },
  {
    name: 'GCash - Recurring',
    paymentType:'wallet',
    paymentFlow: 'redirect',
    countries: ['PH'],
    currencies: ['PHP'],
    recurring: true,
    refunds: true,
    partialRefunds: true,
    captures: false,
    partialCaptures: false,
    chargebacks: false,
    url:'https://docs.adyen.com/payment-methods/gcash?tab=%23recurring_2'
  },
  {
    name: 'giropay',
    paymentType:'onlineBanking',
    paymentFlow: 'redirect',
    countries: ['DE'],
    currencies: ['EUR'],
    recurring: true,
    refunds: true,
    partialRefunds: false,
    captures: false,
    partialCaptures: false,
    chargebacks: false,
    url:'https://docs.adyen.com/payment-methods/giropay'
  },
  {
    name: 'Google Pay',
    paymentType:'wallet',
    paymentFlow: 'direct',
    countries: ['international'],
    currencies: ['multiple'],
    recurring: true,
    refunds: true,
    partialRefunds: true,
    captures: true,
    partialCaptures: true,
    chargebacks: true,
    url:'https://docs.adyen.com/payment-methods/google-pay'
  },
  {
    name: 'GrabPay',
    paymentType:'wallet',
    paymentFlow: 'redirect',
    countries: ['MY', 'PH', 'SG'],
    currencies: ['MYR', 'PHP', 'SGD'],
    recurring: true,
    refunds: true,
    partialRefunds: true,
    captures: false,
    partialCaptures: false,
    chargebacks: false,
    url:'https://docs.adyen.com/payment-methods/grabpay'
  },
  {
    name: 'iDeal',
    paymentType:'onlineBanking',
    paymentFlow: 'redirect',
    countries: ['NL'],
    currencies: ['EUR'],
    recurring: true,
    refunds: true,
    partialRefunds: false,
    captures: false,
    partialCaptures: false,
    chargebacks: false,
    url:'https://docs.adyen.com/payment-methods/ideal'
  },
  {
    name: 'Indonesian bank transfers and convenience stores',
    paymentType:'cashAndAtm',
    paymentFlow: 'voucher',
    countries: ['ID'],
    currencies: ['IDR'],
    recurring: false,
    refunds: false,
    partialRefunds: false,
    captures: false,
    partialCaptures: false,
    chargebacks: false,
    url:'https://docs.adyen.com/payment-methods/doku'
  },
  {
    name: 'Japanese convenience stores',
    paymentType:'cashAndAtm',
    paymentFlow: 'voucher',
    countries: ['JP'],
    currencies: ['JPY'],
    recurring: false,
    refunds: false,
    partialRefunds: false,
    captures: false,
    partialCaptures: false,
    chargebacks: false,
    url:'https://docs.adyen.com/payment-methods/econtext-konbini'
  },
  {
    name: 'Klarna',
    paymentType:'openInvoice',
    paymentFlow: 'redirect/klarna widget',
    countries: ['multiple'],
    currencies: ['multiple'],
    recurring: true,
    refunds: true,
    partialRefunds: true,
    captures: true,
    partialCaptures: true,
    chargebacks: false,
    url:'https://docs.adyen.com/payment-methods/klarna'
  },
  {
    name: 'MB WAY',
    paymentType:'',
    paymentFlow: '',
    countries: [],
    currencies: [],
    recurring: false,
    refunds: false,
    partialRefunds: false,
    captures: false,
    partialCaptures: false,
    chargebacks: false,
    url:''
  },
  {
    name: 'MOLPay',
    paymentType:'onlineBanking',
    paymentFlow: 'redirect',
    countries: ['MY', 'TH'],
    currencies: ['MYR', 'THB'],
    recurring: false,
    refunds: true,
    partialRefunds: false,
    captures: false,
    partialCaptures: false,
    chargebacks: false,
    url:'https://docs.adyen.com/payment-methods/molpay'
  },
  {
    name: 'MoMo Wallet',
    paymentType:'wallet',
    paymentFlow: 'redirect',
    countries: ['VN'],
    currencies: ['VND'],
    recurring: true,
    refunds: true,
    partialRefunds: true,
    captures: false,
    partialCaptures: false,
    chargebacks: false,
    url:'https://docs.adyen.com/payment-methods/momo'
  },
  {
    name: 'Multibanco',
    paymentType:'cashAndAtm',
    paymentFlow: 'voucher',
    countries: ['PT'],
    currencies: ['EUR'],
    recurring: false,
    refunds: false,
    partialRefunds: false,
    captures: false,
    partialCaptures: false,
    chargebacks: false,
    url:'https://docs.adyen.com/payment-methods/multibanco'
  },
  {
    name: 'Oney 3x4x',
    paymentType:'',
    paymentFlow: '',
    countries: [],
    currencies: [],
    recurring: false,
    refunds: false,
    partialRefunds: false,
    captures: false,
    partialCaptures: false,
    chargebacks: false,
    url:''
  },
  {
    name: 'Online banking India',
    paymentType:'onlineBanking',
    paymentFlow: 'redirect',
    countries: ['IN'],
    currencies: ['INR'],
    recurring: false,
    refunds: true,
    partialRefunds: false,
    captures: false,
    partialCaptures: false,
    chargebacks: false,
    url:'https://docs.adyen.com/payment-methods/online-banking-india'
  },
  {
    name: 'Online banking Japan',
    paymentType:'',
    paymentFlow: '',
    countries: [],
    currencies: [],
    recurring: false,
    refunds: false,
    partialRefunds: false,
    captures: false,
    partialCaptures: false,
    chargebacks: false,
    url:''
  },
  {
    name: 'PayMaya',
    paymentType:'wallet',
    paymentFlow: 'redirect',
    countries: ['PH'],
    currencies: ['PHP'],
    recurring: true,
    refunds: true,
    partialRefunds: true,
    captures: true,
    partialCaptures: true,
    chargebacks: true,
    url:'https://docs.adyen.com/payment-methods/paymaya'
  },
  {
    name: 'PayPal',
    paymentType:'payPal',
    paymentFlow: 'direct',
    countries: ['international'],
    currencies: ['multiple'],
    recurring: true,
    refunds: true,
    partialRefunds: true,
    captures: true,
    partialCaptures: true,
    chargebacks: true,
    url:'https://docs.adyen.com/payment-methods/paypal'
  },
  {
    name: 'PayPal Credit',
    paymentType:'payPalCredit',
    paymentFlow: 'direct',
    countries: ['US', 'UK'],
    currencies: ['multiple'],
    recurring: true,
    refunds: true,
    partialRefunds: true,
    captures: true,
    partialCaptures: true,
    chargebacks: true,
    url:'https://docs.adyen.com/payment-methods/paypal'
  },
  {
    name: 'Paytm',
    paymentType:'wallet',
    paymentFlow: 'redirect',
    countries: ['IN'],
    currencies: ['INR'],
    recurring: true,
    refunds: true,
    partialRefunds: true,
    captures: false,
    partialCaptures: false,
    chargebacks: true,
    url:''
  },
  {
    name: 'QiwiWallet',
    paymentType:'',
    paymentFlow: '',
    countries: [],
    currencies: [],
    recurring: false,
    refunds: false,
    partialRefunds: false,
    captures: false,
    partialCaptures: false,
    chargebacks: false,
    url:''
  },
  {
    name: 'RatePAY',
    paymentType:'',
    paymentFlow: '',
    countries: [],
    currencies: [],
    recurring: false,
    refunds: false,
    partialRefunds: false,
    captures: false,
    partialCaptures: false,
    chargebacks: false,
    url:''
  },
  {
    name: 'SEPA Direct Debit',
    paymentType:'directDebit',
    paymentFlow: 'direct',
    countries: ['SEPA countries'],
    currencies: ['EUR'],
    recurring: true,
    refunds: true,
    partialRefunds: false,
    captures: false,
    partialCaptures: false,
    chargebacks: true,
    url:'https://docs.adyen.com/payment-methods/sepa-direct-debit'
  },
  {
    name: 'Sofort',
    paymentType:'onlineBanking',
    paymentFlow: 'redirect',
    countries: ['multiple'],
    currencies: ['multiple'],
    recurring: true,
    refunds: true,
    partialRefunds: true,
    captures: false,
    partialCaptures: false,
    chargebacks: true,
    url:'https://docs.adyen.com/payment-methods/sofort'
  },
  {
    name: 'Swish',
    paymentType:'wallet',
    paymentFlow: 'qrCode',
    countries: ['SE'],
    currencies: ['SEK'],
    recurring: false,
    refunds: true,
    partialRefunds: false,
    captures: false,
    partialCaptures: false,
    chargebacks: false,
    url:'https://docs.adyen.com/payment-methods/swish'
  },
  {
    name: 'Vietnamese online banking',
    paymentType:'onlineBanking',
    paymentFlow: 'redirect',
    countries: ['VN'],
    currencies: ['VND'],
    recurring: false,
    refunds: true,
    partialRefunds: false,
    captures: false,
    partialCaptures: false,
    chargebacks: false,
    url:'https://docs.adyen.com/payment-methods/vietnamese-online-banking'
  },
  {
    name: 'Vipps',
    paymentType:'',
    paymentFlow: '',
    countries: [],
    currencies: [],
    recurring: false,
    refunds: false,
    partialRefunds: false,
    captures: false,
    partialCaptures: false,
    chargebacks: false,
    url:''
  },
  {
    name: 'Wallets India',
    paymentType:'wallet',
    paymentFlow: 'redirect',
    countries: ['IN'],
    currencies: ['INR'],
    recurring: false,
    refunds: true,
    partialRefunds: false,
    captures: false,
    partialCaptures: false,
    chargebacks: false,
    url:'https://docs.adyen.com/payment-methods/wallets-india'
  },
  {
    name: 'WeChat Pay',
    paymentType:'wallet',
    paymentFlow: '',
    countries: ['international'],
    currencies: ['AUD', 'CAD', 'CNY', 'EUR', 'GBP', 'HKD', 'JPY', 'NZD', 'SGD', 'USD'],
    recurring: false,
    refunds: true,
    partialRefunds: true,
    captures: false,
    partialCaptures: false,
    chargebacks: false,
    url:'https://docs.adyen.com/payment-methods/wechat-pay'
  },
  {
    name: 'Zip',
    paymentType:'wallet',
    paymentFlow: 'redirect',
    countries: ['AU'],
    currencies: ['AUD'],
    recurring: true,
    refunds: true,
    partialRefunds: true,
    captures: true,
    partialCaptures: true,
    chargebacks: true,
    url:'https://docs.adyen.com/payment-methods/zip'
  }
]